name: Release to NuGet + Github packages

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '9.0.x'

            - name: Build
              run: dotnet build HypeRate/HypeRate.csproj -c Release

            - name: Pack nugets
              run: dotnet pack HypeRate/HypeRate.csproj -c Release --no-build --output .

            - name: Push to NuGet
              run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

            - name: Push to Github NuGet registry
              run: dotnet nuget push "*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/HypeRate/index.json
